#!/bin/bash

	sum=0
	count=0
	avg=0
	median=0
	medianIndex=0

	TMP1=./TMP1
	echo -e "12\n10\n8\n7\n6" > $TMP1

	while read num
	do
		echo "In Loop"
		echo "num: $num"
		sum=`expr $sum + $num`
		count=`expr $count + 1`
		echo "sum: $sum"
		echo "count: $count"
		echo -e "End of Loop\n"
		avg=`expr $sum / $count`
		echo "average: $avg"
		medianIndex=`expr $count`
		echo "median: $medianIndex"
	done < $TMP1
